services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: edukos-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "EduKos_Dev123!"
    ports:
      - "14333:1433"
    volumes:
      - edukos-sql-data:/var/opt/mssql

  mongo:
    image: mongo:7
    container_name: edukos-mongo
    ports:
      - "27017:27017"
    volumes:
      - edukos-mongo-data:/data/db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edukos-api
    depends_on:
      - db
      - mongo
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=EduKos;User Id=sa;Password=EduKos_Dev123!;TrustServerCertificate=True;"
      Jwt__Key: "THIS_IS_A_VERY_SECURE_SECRET_KEY_123456789"
      Jwt__Issuer: "EduKos"
      Jwt__Audience: "EduKosUsers"
      Jwt__AccessTokenMinutes: "60"
      Jwt__RefreshTokenDays: "7"
      Rtc__BaseUrl: "http://rtc:5060/"
      Rtc__InternalSecret: "EDUKOS_RTC_INTERNAL_SECRET_CHANGE_ME"
      MongoDb__ConnectionString: "mongodb://mongo:27017"
      MongoDb__DatabaseName: "EduKosNonRelational"
      MongoDb__LogsCollection: "logs"
      MongoDb__NotificationsCollection: "notifications"
      MongoDb__ActivityHistoryCollection: "activity_history"
    ports:
      - "5088:8080"

  rtc:
    build:
      context: ./server
      dockerfile: Dockerfile.rtc
    container_name: edukos-rtc
    depends_on:
      - api
    restart: on-failure
    environment:
      RTC_PORT: "5060"
      CLIENT_ORIGIN: "http://localhost:5173"
      EDUKOS_API_URL: "http://api:8080"
      JWT_KEY: "THIS_IS_A_VERY_SECURE_SECRET_KEY_123456789"
      JWT_ISSUER: "EduKos"
      JWT_AUDIENCE: "EduKosUsers"
      RTC_INTERNAL_SECRET: "EDUKOS_RTC_INTERNAL_SECRET_CHANGE_ME"
    ports:
      - "5060:5060"

volumes:
  edukos-sql-data:
  edukos-mongo-data:
