services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: edukos-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "EduKos_Dev123!"
    ports:
      - "14333:1433"
    volumes:
      - edukos-sql-data:/var/opt/mssql

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edukos-api
    depends_on:
      - db
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=EduKos;User Id=sa;Password=EduKos_Dev123!;TrustServerCertificate=True;"
      Jwt__Key: "THIS_IS_A_VERY_SECURE_SECRET_KEY_123456789"
      Jwt__Issuer: "EduKos"
      Jwt__Audience: "EduKosUsers"
      Jwt__AccessTokenMinutes: "60"
      Jwt__RefreshTokenDays: "7"
    ports:
      - "5088:8080"

volumes:
  edukos-sql-data:
